import { z } from "zod";

export const WrittenContractSchema = z.object({
  id: z.string().min(1, "id obligatoriu"),
  contractId: z.string().min(1).optional(),
  contractSignedAt: z.string().optional(),
  contractStartDate: z.string().optional(),
  contractEndDate: z.string().optional(),
  assetName: z.string().optional(),
  assetId: z.string().optional(),
  assetAddress: z.string().optional(),
  ownerId: z.string().optional(),
  title: z.string().min(1, "titlu obligatoriu"),
  subtitle: z.string().optional().default(""),
  documentNumber: z.string().optional().default(""),
  documentDate: z.string().optional().default(""),
  ownerName: z.string().optional().default(""),
  ownerAddress: z.string().optional().default(""),
  ownerContactEmails: z.string().optional().default(""),
  ownerContactPhones: z.string().optional().default(""),
  ownerRegistration: z.string().optional().default(""),
  ownerTaxId: z.string().optional().default(""),
  ownerHeadOffice: z.string().optional().default(""),
  ownerRepresentative: z.string().optional().default(""),
  ownerRepresentativeTitle: z.string().optional().default(""),
  partnerName: z.string().optional().default(""),
  partnerId: z.string().optional(),
  partnerAddress: z.string().optional().default(""),
  partnerEmail: z.string().optional().default(""),
  partnerPhone: z.string().optional().default(""),
  partnerRegistration: z.string().optional().default(""),
  partnerTaxId: z.string().optional().default(""),
  partnerHeadOffice: z.string().optional().default(""),
  partnerRepresentative: z.string().optional().default(""),
  partnerRepresentativeTitle: z.string().optional().default(""),
  rentAmount: z.string().optional().default(""),
  rentAmountText: z.string().optional().default(""),
  tvaPercent: z.string().optional().default(""),
  tvaType: z.string().optional().default(""),
  correctionPercent: z.string().optional().default(""),
  spaceSurface: z.string().optional().default(""),
  intendedUse: z.string().optional().default(""),
  spaceUsage: z.string().optional().default(""),
  invoiceIssueDay: z.string().optional().default(""),
  monthlyInvoiceDay: z.string().optional().default(""),
  invoiceMonthMode: z.string().optional().default(""),
  monthOfRent: z.string().optional().default(""),
  paymentDueDays: z.string().optional().default(""),
  invoiceSendChannels: z.string().optional().default(""),
  indexingMonth: z.string().optional().default(""),
  bankAccount: z.string().optional().default(""),
  bankName: z.string().optional().default(""),
  guaranteeMultiplier: z.string().optional().default(""),
  guaranteeDueDate: z.string().optional().default(""),
  guaranteeForms: z.string().optional().default(""),
  guaranteeBoMultiplier: z.string().optional().default(""),
  utilityPaymentTerm: z.string().optional().default(""),
  latePaymentPenaltyPercent: z.string().optional().default(""),
  latePaymentNotificationFee: z.string().optional().default(""),
  evacuationFee: z.string().optional().default(""),
  storageFee: z.string().optional().default(""),
  nonPaymentTerminationDays: z.string().optional().default(""),
  dailyPenaltyAfterTermination: z.string().optional().default(""),
  denunciationNoticeDays: z.string().optional().default(""),
  denunciationLockMonths: z.string().optional().default(""),
  denunciationPenaltyMonths: z.string().optional().default(""),
  denunciationPenaltyFixed: z.string().optional().default(""),
  abandonPenaltyDescription: z.string().optional().default(""),
  overstayPenaltyPerDay: z.string().optional().default(""),
  confidentialityPenalty: z.string().optional().default(""),
  forceMajeureNoticeDays: z.string().optional().default(""),
  signatureLocation: z.string().optional().default(""),
  body: z.string().min(1, "conținut obligatoriu"),
  notes: z.string().optional().default(""),
  authorEmail: z.string().email().optional(),
  createdAt: z.string().min(1),
  updatedAt: z.string().min(1),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

export const WrittenContractDraftSchema = z.object({
  id: z.string().min(1).optional(),
  contractId: z.string().min(1).optional(),
  contractSignedAt: z.string().optional(),
  contractStartDate: z.string().optional(),
  contractEndDate: z.string().optional(),
  assetName: z.string().optional(),
  assetId: z.string().optional(),
  assetAddress: z.string().optional(),
  ownerId: z.string().optional(),
  title: z.string().min(1, "titlu obligatoriu"),
  subtitle: z.string().optional(),
  documentNumber: z.string().optional(),
  documentDate: z.string().optional(),
  ownerName: z.string().optional(),
  ownerAddress: z.string().optional(),
  ownerContactEmails: z.string().optional(),
  ownerContactPhones: z.string().optional(),
  ownerRegistration: z.string().optional(),
  ownerTaxId: z.string().optional(),
  ownerHeadOffice: z.string().optional(),
  ownerRepresentative: z.string().optional(),
  ownerRepresentativeTitle: z.string().optional(),
  partnerName: z.string().optional(),
  partnerId: z.string().optional(),
  partnerAddress: z.string().optional(),
  partnerEmail: z.string().optional(),
  partnerPhone: z.string().optional(),
  partnerRegistration: z.string().optional(),
  partnerTaxId: z.string().optional(),
  partnerHeadOffice: z.string().optional(),
  partnerRepresentative: z.string().optional(),
  partnerRepresentativeTitle: z.string().optional(),
  rentAmount: z.string().optional(),
  rentAmountText: z.string().optional(),
  tvaPercent: z.string().optional(),
  tvaType: z.string().optional(),
  correctionPercent: z.string().optional(),
  spaceSurface: z.string().optional(),
  intendedUse: z.string().optional(),
  spaceUsage: z.string().optional(),
  invoiceIssueDay: z.string().optional(),
  monthlyInvoiceDay: z.string().optional(),
  invoiceMonthMode: z.string().optional(),
  monthOfRent: z.string().optional(),
  paymentDueDays: z.string().optional(),
  invoiceSendChannels: z.string().optional(),
  indexingMonth: z.string().optional(),
  bankAccount: z.string().optional(),
  bankName: z.string().optional(),
  guaranteeMultiplier: z.string().optional(),
  guaranteeDueDate: z.string().optional(),
  guaranteeForms: z.string().optional(),
  guaranteeBoMultiplier: z.string().optional(),
  utilityPaymentTerm: z.string().optional(),
  latePaymentPenaltyPercent: z.string().optional(),
  latePaymentNotificationFee: z.string().optional(),
  evacuationFee: z.string().optional(),
  storageFee: z.string().optional(),
  nonPaymentTerminationDays: z.string().optional(),
  dailyPenaltyAfterTermination: z.string().optional(),
  denunciationNoticeDays: z.string().optional(),
  denunciationLockMonths: z.string().optional(),
  denunciationPenaltyMonths: z.string().optional(),
  denunciationPenaltyFixed: z.string().optional(),
  abandonPenaltyDescription: z.string().optional(),
  overstayPenaltyPerDay: z.string().optional(),
  confidentialityPenalty: z.string().optional(),
  forceMajeureNoticeDays: z.string().optional(),
  signatureLocation: z.string().optional(),
  body: z.string().min(1, "conținut obligatoriu"),
  notes: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

export type WrittenContract = z.infer<typeof WrittenContractSchema>;
export type WrittenContractInput = Omit<
  WrittenContract,
  "id" | "createdAt" | "updatedAt"
> & {
  id?: string;
  createdAt?: string;
};
export type WrittenContractDraft = z.infer<typeof WrittenContractDraftSchema>;
