name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --silent

      - name: Test - fetch contracts by assetId
        run: npx tsx __tests__/fetch-contracts-by-assetid.test.ts

      - name: Test - deposits
        run: npx tsx __tests__/deposits.test.ts

      - name: Test - invoice month mode runner
        run: npx tsx __tests__/invoice-month-mode-runner.ts
